name: Build and push DocsGPT Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Build and push application Docker images
        uses: docker/build-push-action@v4
        with:
          file: './application/Dockerfile'
          platforms: linux/amd64
          context: ./application
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: |
            ghcr.io/${{ github.repository_owner }}/docsgpt_application:latest
            ghcr.io/${{ github.repository_owner }}/docsgpt-application:latest
