name: Build and push DocsGPT-FE Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v4
        with:
          file: './frontend/Dockerfile'
          platforms: linux/amd64,linux/arm64
          context: ./frontend
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: |
            ${{ github.repository_owner }}/docsgpt:fe-latest
            ghcr.io/${{ github.repository_owner }}/docsgpt-fe:latest
